name: iOS Release
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET 9.0.100
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.100

      - name: Clean .NET 10
        run: |
          rm -rf /Users/runner/.dotnet/sdk/10.* || true
          rm -rf /Users/runner/.dotnet/sdk-manifests/10.* || true

      - name: Install MAUI
        run: dotnet workload install maui --version 9.0.100

      - name: Clean old build
        run: |
          rm -rf obj bin || true
          find . -type d -name obj -exec rm -rf {} + || true
          find . -type d -name bin -exec rm -rf {} + || true

      - name: Restore
        run: dotnet restore FlexiPortal.Mobile.csproj -p:EnableWindowsTargeting=true -p:CheckEolWorkloads=false

      - name: Build iOS IPA
        run: dotnet publish FlexiPortal.Mobile.csproj -f net9.0-ios -c Release -r ios-arm64 -p:BuildIpa=true -p:EnableCodeSigning=false -p:EnableWindowsTargeting=true -p:CheckEolWorkloads=false -p:RunAOTCompilation=false -p:PlatformTarget=AnyCPU

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: "**/*.ipa"
